replicaCount: 2

image:
  repository: acrinterview.azurecr.io/simple-web
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

keda:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpu:
    targetAverageUtilization: 80
  memory:
    targetAverageUtilization: 80
  schedule:
    start: "0 8 * * *"
    end: "1 0 * * *"
    offReplicas: 0

ingress:
  enabled: true
  className: ""
  annotations: {}
  host: ""
  path: /oleksandr
  pathType: Prefix
  tls: []
